### ISSUE TITLE
请问系统托盘图标是怎么设置的？

### ISSUE THREAD

**Issue by yujqiao** [wangzme/dotfiles#1]
是使用了什么图标集吗？在哪个部分设置的？
我这边 nm-applet 的图标可没这么好看啊……
顺便问一下 polybar 的图标来自哪个字体？Nerd Font 是个太大的图标集合了

**Comment by wzhchin** [comment]
1. 托盘图标有的是自己做的，大部分是从别的地方搞来的。图标主题在我的 AWEL 仓库里面。
2. 字体是苹果的 SF PRO ，如果你看了 polybar 的配置文件你会在里面发现这个信息。

Edit Nerd Font 有一个纯图标的字体，大小不到 1兆。如果你在使用 Archlinux 的话，请安装 aur/ttf-nerd-fonts-symbols 。

**Comment by wzhchin** [comment]
图标仓库 AWEL 为了使 polybar 看起来统一只有几个状态栏图标，已经被我删除了。
但是可以直接使用这个仓库中的` {dark, light}/icons/AWEL-{Nior, Lumine}`，默认依赖 Qogir, Arc 这两个图标主题。
如果不喜欢 Qogir, Arc 的话可以自己修改主题文件夹中的 `index.theme` 文件。
