### ISSUE TITLE
Icons are not showing in polybar

### ISSUE THREAD

**Issue by johnwuelk** [wangzme/dotfiles#10]
I want to apply your beautiful light theme. I installed Qogir and arc theme as required and everything seems to work except the icons in the polybar not showing. I put the "AWEL-Nior" folder in ~/.icons. Or does that folder belong somewhere else?
And in your polybar config I don't know what the %icon% variable stands for because I don't see it assigned anywhere. Thanks for your help.

**Comment by wzhchin** [comment]
Try to install SF Pro font, it is  provides the font icon for polybar, which is a font by Apple so you need to get it by yourself.

**Comment by johnwuelk** [comment]
I actually succeeded with Nerds Font and used it as the icon font. Thanks nonetheless.

**Comment by wzhchin** [comment]
Okay, if you have any other questions, I will reopen this issue.
