### ISSUE TITLE
有详细的安装指南吗？

### ISSUE THREAD

**Issue by haoqing-yan** [wangzme/dotfiles#11]
我把你整个配置拷贝下来后，重新加载的时候出了点问题

**Comment by wzhchin** [comment]
抱歉，目前还没有。

现在只是努力给一些正在配置 i3wm 的用户一些点子吧。

具体的配置包括安装指南恐怕会在 10.1 时重新弄一下。

**Comment by haoqing-yan** [comment]
好的，谢谢呀！

**Comment by ypli0629** [comment]
期待啊

**Comment by wzhchin** [comment]
国庆有点忙, 这个给鸽了, 这几天在努力补...

**Comment by ypli0629** [comment]
> 国庆有点忙, 这个给鸽了, 这几天在努力补...

期待，最近刚开始入 i3 的坑

**Comment by haoqing-yan** [comment]
辛苦了

**Comment by wzhchin** [comment]
可能是完成了。

如果有什么问题的话，我会再打开这个问题。
