### ISSUE TITLE
托盘图标未能正常显示

### ISSUE THREAD

**Issue by bincat233** [wangzme/dotfiles#14]
怀疑是不是因为我是高分屏的原因...
请问有什么方法可以帮助调试图标吗

**Comment by bincat233** [comment]
![image](https://user-images.githubusercontent.com/20554448/99771644-6cea5880-2b44-11eb-987f-788882748905.png)

**Comment by bincat233** [comment]
![image](https://user-images.githubusercontent.com/20554448/99771738-92776200-2b44-11eb-8979-a7813b7ba317.png)

**Comment by bincat233** [comment]
我看到icons/panel 目录下是有 Flameshot 和 clipit 的 这两个不知道为什么没能正常显示

**Comment by wzhchin** [comment]
我做了很少一部分的图标，仅仅是我日常使用应用的子范围。

那个剪切板是 copyq 的图标。

**需要使用 qt5ct 指定主题图标**，我会把这部分补充到 readme 中。

如果需要哪些图标的话，请在下面评论中指出，我可能会在空闲时间去做。

**Comment by bincat233** [comment]
@aeghn 找到原因了, clipit-trayicon需要放在apps目录下面
