### ISSUE TITLE
启动后输出大量的警告，不知是否是字体问题

### ISSUE THREAD

**Issue by AmberisMyShiba** [wangzme/dotfiles#16]
warn: Dropping unmatched character 􀌈 (U+100308) in ' 􀌈 '
warn: Dropping unmatched character 􀓘 (U+1004d8) in ' 􀓘 '
warn: Dropping unmatched character 􀇬 (U+1001ec) in '  􀇬'
warn: Dropping unmatched character 􀊤 (U+1002a4) in ' 􀊤 40% '

**Comment by wzhchin** [comment]
是的，考虑自己找一下 SF Pro 字体吧。

不过这个没啥影响。

**Comment by FrazeWu** [comment]
我也是，不过我装了SF PRO字体了 log也能显示也能找到字体，不过就是符号显示不出来。

**Comment by FrazeWu** [comment]
notice: Parsing config file: /home/fa/.config/polybar/config
warn: The config parameter 'settings.throttle-input-for' is deprecated, it will be removed in the future. Please remove it from your config
error: Disabling module "right" (reason: module/right.content is empty or undefined)
error: module/mpd: Connection refused
error: Disabling module "netspeed" (reason: Invalid network interface "wlp2s0")
notice: pulseaudio: using default sink alsa_output.pci-0000_00_1f.3.analog-stereo
error: Disabling module "headphone" (reason: Missing section "module/headphone")
error: module/mpd: Connection refused
notice: Loaded font "sf pro display:style=regular:size=12" (name=SF Pro Display, offset=3, file=/usr/share/fonts/OTF/SF-Pro-Display-Regular.otf)
warn: Ignoring restack of i3 window (not needed when `override-redirect = false`)
warn: Dropping unmatched character 􀌈 (U+100308) in ' 􀌈 '
warn: Dropping unmatched character 􀓘 (U+1004d8) in ' 􀓘 '
warn: Dropping unmatched character 􀛨 (U+1006e8) in '  􀛨'
warn: Dropping unmatched character 􀆭 (U+1001ad) in '􀆭 100% '
warn: Dropping unmatched character 􀊤 (U+1002a4) in ' 􀊤 46% '
error: module/mpd: Connection refused
error: module/mpd: Connection refused
warn: Dropping unmatched character 􀌈 (U+100308) in ' 􀌈 '
warn: Dropping unmatched character 􀓘 (U+1004d8) in ' 􀓘 '
warn: Dropping unmatched character 􀛨 (U+1006e8) in '  􀛨'
warn: Dropping unmatched character 􀆭 (U+1001ad) in '􀆭 100% '

**Comment by wzhchin** [comment]
@fz-wu 确定这个字体里面含有图标是吗？

有的版本里的 sf pro 字体是不含有图标的

**Comment by wzhchin** [comment]
长时间无活动，关闭。
