### ISSUE TITLE
Invisible slider in firefox

### ISSUE THREAD

**Issue by sirikid** [wangzme/dotfiles#4]
https://projectfluent.org

AWEL-Lumine:
![image](https://user-images.githubusercontent.com/4840430/66258939-d928c200-e7b3-11e9-85b7-59339c5f5a7f.png)
Breeze:
![image](https://user-images.githubusercontent.com/4840430/66258945-f52c6380-e7b3-11e9-9108-6dcf48b21a4e.png)

**Comment by wzhchin** [comment]
My hard drive was broken lately and the source code for this theme is lost, so I may not be able to fix it.
BTW I am making a theme based on the numix gtk theme now, which will replace this theme in the future.
