### ISSUE TITLE
Very nice choosen icons!

### ISSUE THREAD

**Issue by ApolloBian** [wangzme/dotfiles#5]
I have a very similar theme setup but damn yours just feels so much polished!
![image](https://user-images.githubusercontent.com/13659369/67255807-85f28700-f4b6-11e9-9c9c-71cff9011d60.png)
out of curiosity, what is this app you are using?

**Comment by ApolloBian** [comment]
the last one

**Comment by wzhchin** [comment]
Thanks, I am very glad you like it.


This tool is called gtk3-widget-factory. Its purpose is to demonstrate many GTK+ widgets in a form that is useful to GTK+ theme developers.

If you have installed the package gtk3, you should be able to use this tool, I guess.

**Comment by ApolloBian** [comment]
@wzhaen Thanks, it looks very cool. (I also realized that my gtk theme sucks immediately)
