### ISSUE TITLE
請問border字體從哪裏可以找到

### ISSUE THREAD

**Issue by mowind** [wangzme/dotfiles#6]

**Comment by wzhchin** [comment]
当前的 commit 中没有使用 border 字体，看到的图标大部分都是由 SF PRO 提供的。
SF PRO 请自己尝试从 macOS 中提取。

**Comment by mowind** [comment]
polybar module.ini `format-prefix`有大量的乱码，是因为缺少SF Pro字体吗？
![图片](https://user-images.githubusercontent.com/2201590/70313680-0ac01700-1851-11ea-89f7-309effae0acb.png)

**Comment by wzhchin** [comment]
对，首先既然你没装这个字体，那么有很大可能出现这种标志的（如果别的字体也没有这个字符的话）。如果装了 SF PRO 还出现这种情况的话，可能需要在编辑器设置中或者在 fontconfig 中指明这个字体。

**Comment by mowind** [comment]
了解，谢谢！

**Comment by DrKyro** [comment]
![2020-07-06_14-17](https://user-images.githubusercontent.com/20229707/86561527-6d1df900-bf93-11ea-9a7c-a6b203ede1e4.png)是这个字体吗，我安装了字体polybar的字变粗了，但是图标还是没有

**Comment by DrKyro** [comment]
![2020-07-06_14-19](https://user-images.githubusercontent.com/20229707/86561651-bcfcc000-bf93-11ea-9f23-75ed33411f9b.png)
接上
