### ISSUE TITLE
sf pro plus

### ISSUE THREAD

**Issue by paralevi** [wangzme/dotfiles#7]
`font-1 = "sf pro plus:style=regular:size=12;3"`
请教一下这个字体真的存在吗？还是需要通过一些patch手段。检索了很久，尝试了各种[公开的字体repo](https://github.com/blaisck/sfwin)，都没有找到同名的；polybar图标似乎也因此不能正确显示。

p.s.在知乎上蹲守了很久这个repo，感谢您的付出。

**Comment by wzhchin** [comment]
不好意思，这个图标字体是我自己画得，主要是为了补全 SF PRO，一会我更新一下说明（我现在全部用得自己画的另一套字体，这个东西已经找不到了）。
里面只有几个图标，包括电池和几个软件图标。安装了 SF PRO 后应该就会显示绝大多数图标，除了一部分电池的状态。因为原版 SF PRO 应该只有有满电等几个状态，缺少中间状态。

**Comment by paralevi** [comment]
我用了sf pro icons，发现绝大多数图标还是不能正确展示，如network，volume等
```
warn: Dropping unmatched character 􀁶 (U+100076)
warn: Dropping unmatched character 􀁸 (U+100078)
warn: Dropping unmatched character 􀌈 (U+100308)
warn: Dropping unmatched character 􀊢 (U+1002a2)
```

**Comment by wzhchin** [comment]
你是直接用的我的配置文件还是想只使用这个图标字体？

**Comment by paralevi** [comment]
我在配置文件上做了些修改；如果能提供这个字体，再好不过啦。否则我只能根据语义用`Font Awesome`之类逐一替换，工作量不小。感谢！

**Comment by wzhchin** [comment]
抱歉，这个字体是有版权的，你可以尝试自己从 MacOS 中提取。
